update patches to match upstream

diff --git a/patches/addzostomakefile.patch b/patches/addzostomakefile.patch
--- a/patches/addzostomakefile.patch
+++ b/patches/addzostomakefile.patch
@@ -1,30 +1,30 @@
 diff --git a/Makefile b/Makefile
-index 9b5451d..6c3f937 100644
+index e8e6bcf..7221ef4 100644
 --- a/Makefile
 +++ b/Makefile
-@@ -149,7 +149,7 @@ clean:
+@@ -147,7 +147,7 @@ clean:
  #------------------------------------------------------------------------------
  # make install is validated only for Linux, macOS, Hurd and some BSD targets
  #------------------------------------------------------------------------------
--ifneq (,$(filter $(shell uname),Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD DragonFly NetBSD MSYS_NT Haiku AIX))
-+ifneq (,$(filter $(shell uname),Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD DragonFly NetBSD MSYS_NT Haiku AIX OS/390))
+-ifneq (,$(filter Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD DragonFly NetBSD MSYS_NT% CYGWIN_NT% Haiku AIX,$(shell sh -c 'MSYSTEM="MSYS" uname') ))
++ifneq (,$(filter Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD DragonFly NetBSD MSYS_NT% CYGWIN_NT% Haiku AIX OS/390,$(shell sh -c 'MSYSTEM="MSYS" uname') ))
  
  HOST_OS = POSIX
  
-diff --git i/lib/Makefile w/lib/Makefile
-index a4cf61a..15636a1 100644
---- i/lib/Makefile
-+++ w/lib/Makefile
-@@ -77,6 +77,8 @@ ifeq ($(UNAME), Darwin)
+diff --git a/lib/Makefile b/lib/Makefile
+index a6a0eb0..dfe9e31 100644
+--- a/lib/Makefile
++++ b/lib/Makefile
+@@ -83,6 +83,8 @@ ifeq ($(UNAME_TARGET_SYSTEM), Darwin)
  else
-   ifeq ($(UNAME), AIX)
+   ifeq ($(UNAME_TARGET_SYSTEM), AIX)
      SONAME_FLAGS =
-+  else ifeq ($(UNAME), OS/390)
++  else ifeq ($(UNAME_TARGET_SYSTEM), OS/390)
 +    SONAME_FLAGS =
    else
      SONAME_FLAGS = -Wl,-soname=libzstd.$(SHARED_EXT).$(LIBVER_MAJOR)
    endif
-@@ -160,7 +162,7 @@ $(ZSTD_DYNLIB): $(ZSTD_DYNLIB_OBJ)
+@@ -166,7 +168,7 @@ $(ZSTD_DYNLIB): $(ZSTD_DYNLIB_OBJ)
  	$(if $(filter -DZSTD_MULTITHREAD,$(CPPFLAGS)),\
      @echo compiling multi-threaded dynamic library $(LIBVER),\
      @echo compiling single-threaded dynamic library $(LIBVER))
@@ -33,12 +33,50 @@ index a4cf61a..15636a1 100644
  	@echo creating versioned links
  	ln -sf $@ libzstd.$(SHARED_EXT_MAJOR)
  	ln -sf $@ libzstd.$(SHARED_EXT)
-@@ -249,7 +251,7 @@ clean:
+@@ -255,7 +257,7 @@ libzstd-nomt: $(ZSTD_NOMT_FILES)
+         echo "Error: Found zstdmt in list."; \
+         exit 1; \
+     fi
+-	$(CC) $(FLAGS) $^ $(LDFLAGS) $(SONAME_FLAGS) -o $@
++	$(CC) $(FLAGS) $^ $(LDFLAGS) $(SONAME_FLAGS) -o $@ $(LIBS)
+ 
+ .PHONY: clean
+ clean:
+@@ -268,7 +270,7 @@ clean:
  #-----------------------------------------------------------------------------
  # make install is validated only for below listed environments
  #-----------------------------------------------------------------------------
--ifneq (,$(filter $(UNAME),Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD NetBSD DragonFly SunOS Haiku AIX))
-+ifneq (,$(filter $(UNAME),Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD NetBSD DragonFly SunOS Haiku AIX OS/390 ))
+-ifneq (,$(filter Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD NetBSD DragonFly SunOS Haiku AIX MSYS_NT% CYGWIN_NT%,$(UNAME)))
++ifneq (,$(filter Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD NetBSD DragonFly SunOS Haiku AIX MSYS_NT% CYGWIN_NT% OS/390,$(UNAME)))
  
  lib: libzstd.pc
  
+diff --git a/programs/Makefile b/programs/Makefile
+index f4af5e9..e9b7c6a 100644
+--- a/programs/Makefile
++++ b/programs/Makefile
+@@ -345,7 +345,7 @@ include $(wildcard $(DEPFILES))
+ #-----------------------------------------------------------------------------
+ # make install is validated only for Linux, macOS, BSD, Hurd and Solaris targets
+ #-----------------------------------------------------------------------------
+-ifneq (,$(filter Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD NetBSD DragonFly SunOS Haiku AIX MSYS_NT% CYGWIN_NT%,$(UNAME)))
++ifneq (,$(filter Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD NetBSD DragonFly SunOS Haiku AIX MSYS_NT% CYGWIN_NT% OS/390,$(UNAME)))
+ 
+ HAVE_COLORNEVER = $(shell echo a | egrep --color=never a > /dev/null 2> /dev/null && echo 1 || echo 0)
+ EGREP_OPTIONS ?=
+@@ -414,15 +414,10 @@ install:
+ 	[ -e $(DESTDIR)$(MAN1DIR) ] || $(INSTALL) -d -m 755 $(DESTDIR)$(MAN1DIR)/
+ 	@echo Installing binaries
+ 	$(INSTALL_PROGRAM) zstd$(EXT) $(DESTDIR)$(BINDIR)/zstd$(EXT)
+-	ln -sf zstd$(EXT) $(DESTDIR)$(BINDIR)/zstdcat$(EXT)
+-	ln -sf zstd$(EXT) $(DESTDIR)$(BINDIR)/unzstd$(EXT)
+-	ln -sf zstd$(EXT) $(DESTDIR)$(BINDIR)/zstdmt$(EXT)
+ 	$(INSTALL_SCRIPT) zstdless $(DESTDIR)$(BINDIR)/zstdless
+ 	$(INSTALL_SCRIPT) zstdgrep $(DESTDIR)$(BINDIR)/zstdgrep
+ 	@echo Installing man pages
+ 	$(INSTALL_MAN) zstd.1 $(DESTDIR)$(MAN1DIR)/zstd.1
+-	ln -sf zstd.1 $(DESTDIR)$(MAN1DIR)/zstdcat.1
+-	ln -sf zstd.1 $(DESTDIR)$(MAN1DIR)/unzstd.1
+ 	$(INSTALL_MAN) zstdgrep.1 $(DESTDIR)$(MAN1DIR)/zstdgrep.1
+ 	$(INSTALL_MAN) zstdless.1 $(DESTDIR)$(MAN1DIR)/zstdless.1
+ 	@echo zstd installation completed
